





select * from customer limit 10;

--Q1. What is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than avg purchase amount?
select customer_id, purchase_amount 
from customer
where discount_applied = 'Yes' and purchase